pipeline {
    agent { label 'windows' }

    environment {
        SPA_DIR  = 'CoffeShop.Frontend'
        API_URL  = 'https://rg-coffeeshop-api-ignacio0828-eyh3drgfdcbmc8gu.centralus-01.azurewebsites.net'
        SITE_URL = 'https://coffeshopwebignacio0828.z19.web.core.windows.net'
    }

    stages {
        stage('Build SPA') {
            steps {
                dir(env.SPA_DIR) {
                    bat 'npm ci'
                    bat 'set VITE_API_BASE_URL=%API_URL%&& npm run build'
                }
            }
        }

        stage('Publish SPA') {
            steps {
                withCredentials([string(credentialsId: 'web-sas', variable: 'SAS')]) {
                    dir(env.SPA_DIR) {
                        powershell '''
                            $dest = 'https://coffeshopwebignacio0828.blob.core.windows.net/$web' + $env:SAS
                            azcopy sync dist $dest --recursive --delete-destination=true
                        '''
                    }
                }
            }
        }
    }
}
