// <auto-generated />
using CoffeShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeShop.Data.Migrations
{
    [DbContext(typeof(CoffeShopDbContext))]
    [Migration("20260721205427_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeShop.Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "American",
                            Price = 50.00m,
                            Sku = "HOT-AME-01"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Latte",
                            Price = 65.00m,
                            Sku = "HOT-LAT-02"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Capuccino",
                            Price = 60.00m,
                            Sku = "HOT-CAP-03"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Taro",
                            Price = 80.00m,
                            Sku = "HOT-TAR-04"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Natural Chai",
                            Price = 90.00m,
                            Sku = "HOT-CHA-05"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Iced Latte",
                            Price = 70.00m,
                            Sku = "COL-LAT-06"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Iced American",
                            Price = 60.00m,
                            Sku = "COL-AME-07"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Iced Taro",
                            Price = 85.00m,
                            Sku = "COL-TAR-08"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Iced Chai",
                            Price = 95.00m,
                            Sku = "COL-CHA-09"
                        });
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostumerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("CoffeShop.Data.Entities.Product", "product")
                        .WithMany("inventoryItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.Order", b =>
                {
                    b.HasOne("CoffeShop.Data.Entities.User", "User")
                        .WithOne("Order")
                        .HasForeignKey("CoffeShop.Data.Entities.Order", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.OrderLine", b =>
                {
                    b.HasOne("CoffeShop.Data.Entities.Order", "Order")
                        .WithMany("orderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.Order", b =>
                {
                    b.Navigation("orderLines");
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.Product", b =>
                {
                    b.Navigation("inventoryItems");
                });

            modelBuilder.Entity("CoffeShop.Data.Entities.User", b =>
                {
                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
